const drug = {
  list: {
    id: "고유 키",
    drug_name: "이름",
    sympthon: "증상",
    side_effect: "부작용",
    major_countries: "원산지",
    price_unit: "판매 단위(g)",
    price: "가격",
  },
  drug_list: [
    {
      id: 0,
      drug_name: "필로폰",
      sympthon: "각성효과,성욕증가,집중력증가,인지능력증가",
      side_effect: "의존성,내성,우울증,온몸 상처,염증",
      img_url: "https://cdn.daejonilbo.com/news/photo/202305/2062932_479560_2405.jpg",
      major_countries: "일본",
      price_unit: "1g",
      price: "57,960원",
    },
    {
      id: 1,
      drug_name: "아편(양귀비)",
      sympthon: "쾌락감",
      side_effect: "도파민 과다분비로 식욕부진,수명장애",
      img_url: "https://media.istockphoto.com/id/1149368695/ko/%EC%82%AC%EC%A7%84/%EC%A0%90%ED%86%A0-%EA%B7%B8%EB%A6%87%EC%9D%98-%EB%B6%84%EB%A7%90%EA%B3%BC-%EC%96%91-%EA%B7%80-%EB%B9%84-%EC%94%A8%EC%95%97-%EB%98%90%EB%8A%94-khus-%EB%98%90%EB%8A%94-%EC%95%84%ED%8E%B8-%EC%96%91-%ED%94%BC-%EB%98%90%EB%8A%94-%EC%A0%9C%EB%B9%B5-%EC%A2%85%EC%9E%90-%EC%96%91-%EA%B7%80-%ED%92%80%EC%9D%98-%EB%82%98%EB%AC%B4-%ED%91%9C%EB%A9%B4%EC%97%90-%EC%A0%90%ED%86%A0-%EA%B7%B8%EB%A6%87%EC%9D%98-%EB%8B%AB%EC%8A%B5%EB%8B%88%EB%8B%A4.jpg?s=612x612&w=0&k=20&c=m1EoiTablZft2sB451rDxdZC--l4v8NAqXr9KZOXRiM=",
      major_countries: "중국",
      price_unit: "1g",
      price: "21,735원",
    },
    {
      id: 2,
      drug_name: "코카인",
      sympthon: "쾌락,에너지증가",
      side_effect: "혈압,체온상승,경련,불안,편집증,초조함",
      img_url: "https://image.dongascience.com/Photo/2021/10/7c20f8c6cbb57900facbf4ff9ac49602.jpg",
      major_countries: "페루,콜롬비아",
      price_unit: "1g",
      price: "86,940원",
    },
    {
      id: 3,
      drug_name: "헤로인",
      sympthon: "쾌락",
      side_effect: "불안,불면,고민,침울,구토,설사",
      img_url: "https://femiwiki-uploaded-files-thumb.s3.amazonaws.com/3/38/%ED%97%A4%EB%A1%9C%EC%9D%B8.jpg/1200px-%ED%97%A4%EB%A1%9C%EC%9D%B8.jpg",
      major_countries: "베트남,태국 등 동남아",
      price_unit: "1g",
      price: "201,050원",
    },
    {
      id: 4,
      drug_name: "대마초",
      sympthon: "심신변화,감각강화,쾌락",
      side_effect: "감각증폭,환각,공포심,기억력저하",
      img_url: "https://ichef.bbci.co.uk/news/640/cpsprodpb/5B40/production/_102106332_gettyimages-909445196.jpg",
      major_countries: "파라과이,멕시코",
      price_unit: "1g",
      price: "20,097원",
    },
    {
      id: 5,
      drug_name: "MDMA",
      sympthon: "흥분,쾌락",
      side_effect: "도취,식욕상실,변비,혼수,자아통제 불가능",
      img_url: "https://d2jx2rerrg6sh3.cloudfront.net/image-handler/picture/2019/4/By_Hans_Verburg.jpg",
      major_countries: "네덜란드",
      price_unit: "2g",
      price: "37,674원",
    },
    {
      id: 6,
      drug_name: "케타민",
      sympthon: "쾌락,각성제",
      side_effect: "몽롱함,환각,흥분,헛소리",
      img_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsh9wPpq91xHxd__xAxVVo1Y5rLG_PbBo-Jg&usqp=CAU",
      major_countries: "미얀마,태국,라오스",
      price_unit: "1g",
      price: "31,878원",
    },
    {
      id: 7,
      drug_name: "메스칼린",
      sympthon: "시각적변화",
      side_effect: "환각,기억력상실",
      img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Synthetic_mescaline_powder_i2001e0151_ccby3.jpg/300px-Synthetic_mescaline_powder_i2001e0151_ccby3.jpg",
      major_countries: "네덜란드",
      price_unit: "1g",
      price: "201,050원",
    },
    {
      id: 8,
      drug_name: "크라톰",
      sympthon: "각성제,진정제",
      side_effect: "불면,환각,피로",
      img_url: "https://archive.seattlen.com/data/file/News/1136122415_NnSr9kRf_kratom-capsules.jpg",
      major_countries: "필리핀,뉴기니",
      price_unit: "1kg",
      price: "201,050원",
    },
    {
      id: 9,
      drug_name: "옥시콘틴",
      sympthon: "심리적안정,쾌락",
      side_effect: "두통,심신변화,환각",
      img_url: "https://assets.medpagetoday.net/media/images/52xxx/52431.jpg",
      major_countries: "미국",
      price_unit: "1g",
      price: "147,437원",
    },
    {
      id: 10,
      drug_name: "DMT",
      sympthon: "호로몬변화,심리변화,쾌락",
      side_effect: "환각,기억력저하,헛소리,두통",
      img_url: "https://cdn.adf.org.au/media/images/DMT.width-1524.jpg",
      major_countries: "중국",
      price_unit: "1g",
      price: "134,033원",
    },
    {
      id: 11,
      drug_name: "펜타닐",
      sympthon: "환각,진통제",
      side_effect: "구역질,졸음,인지기능장애,섬망,기립성저혈압",
      img_url: "https://image.jtbcplus.kr/data/contents/jam_photo/202211/22/ea5e6eac-a97f-47bd-9134-d175e10a0d3d.jpg",
      major_countries: "중국",
      price_unit: "1g",
      price: "201,050원",
    },
  ],
};

export default drug;